swagger: '2.0'
info:
  version: 2.0.0
  title: Trade License Calculation APIs
  description: |
    APIs available for Trade License
      - Calculate Trade License.
  contact:
    name: eGovernments Foundation
    email: contacts@egovernments.org
schemes:
  - https
basePath: /tl-calculator/
paths:
  /v1/_calculate:
    post:
      summary: Calculates Trade License and generates the respective demands in the system.
      description: Calculate Trade License Fee based on criteria.
      tags:
        - Trade License Calculation
      parameters:
        - name: calculationReq
          in: body
          description: required parameters have to be populated
          required: true
          schema:
            $ref: '#/definitions/CalculationReq'
      responses:
        '200':
          description: Success response with calculated tax amount.
          schema:
            $ref: '#/definitions/CalculationRes'
        '400':
          description: Error response in case of failures.
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes'
  /v1/_getbill:
    post:
      summary: Updates demand with time based penalty if applicable and Generates bill for the given criteria.
      description: Generates bill for payment.
      tags:
        - Trade License Bill
      parameters:
        - $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/parameters/requestInfo'
        - $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/parameters/tenantId'
        - name: applicationNumber
          in: query
          description: Unique Trade application number.
          required: true
          type: string
      responses:
        '200':
          description: Success response calculated tax amount.
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/billingservice/contracts/v1-0-0.yml#/definitions/Bill'
        '400':
          description: Error response in case of failures.
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes'
  /billingslab/_search:
    post:
      summary: Get the list of properties defined in the system for trade license calculation.
      description: |
        Get the properties list based on the input parameters.
      tags:
        - BillingSlab
      parameters:
        - $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/parameters/requestInfo'
        - $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/tenantId'
        - name: active
          in: query
          description: True will be set in cases where only active properties are needed and False will be set when inactive properties are needed and no value will be set when all properties are needed.
          required: false
          type: boolean
          format: varchar
          allowEmptyValue: true
        - name: propertyId
          in: query
          description: Primary key of Property object.
          required: false
          type: string
          format: varchar
        - name: assessmentNumber
          in: query
          required: false
          description: The unique reference number for a property.
          type: string
          minLength: 4
          maxLength: 128
          exclusiveMinimum: true
          exclusiveMaximum: false
        - name: oldAssessmentNumber
          in: query
          required: false
          description: The unique old assessment no for a Property.
          type: string
          minLength: 4
          maxLength: 128
          exclusiveMinimum: true
          exclusiveMaximum: false
        - name: locality
          in: query
          description: Locality boundary where the property is located.
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/BillingSlabRes'
        '400':
          description: Invalid input.
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
  /billingslab/_create:
    post:
      summary: Create new billing slabs for trade license calculation.
      description: API to billing slabs for trade license calculation.
      tags:
        - BillingSlab
      parameters:
        - name: billingSlab
          in: body
          description: Details for the new slab + RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/BillingSlabReq'
      responses:
        '201':
          description: Billing Slab(s) created sucessfully
          schema:
            $ref: '#/definitions/BillingSlabRes'
        '400':
          description: Billing Slab(s) creation failed
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
  /billingslab/_update:
    post:
      summary: Update existing billing slabs.
      description: Updates a given billing slab with new properties
      parameters:
        - name: billingSlab
          in: body
          description: Request header for the update of billing slab.
          required: true
          schema:
            $ref: '#/definitions/BillingSlab'
      tags:
        - BillingSlab
      responses:
        '200':
          description: Update Billing Slab(s) successful
          schema:
            $ref: '#/definitions/BillingSlab'
        '400':
          description: Update Billing Slab(s) failed
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
definitions:
  CalulationCriteria:
    description: Either tradelicense object or the application number is mandatory apart from tenantid.
    type: object
    properties:
      tradelicense:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/rainmaker/trade-license/tl-service.yml#/definitions/TradeLicense'
      applicationNumber:
        type: string
        minLength: 2
        maxLength: 64
      tenantId:
        type: string
        minLength: 2
        maxLength: 256
    required:
      - tenantId
  Calculation:
    type: object
    properties:
      applicationNumber:
        type: string
        description: TradeLicense application number.
      totalAmount:
        type: number
        format: double
        description: Total payable tax amount.
      penalty:
        type: number
        format: double
        description: Total Penality if applicable.
      exemption:
        type: number
        format: double
        description: Total Exemption amount if applicable.
      rebate:
        type: number
        format: double
        description: Total Rebate amount if applicable.
      tenantId:
        type: string
        minLength: 2
        maxLength: 256
  BillingSlab:
    type: object
    properties:
      tenantId:
        type: string
        description: Unique ulb identifier
        maxLength: 128
        minLength: 4
      id:
        type: string
        description: unique identifier of the billing slab uuid
        maxLength: 64
        minLength: 2
      licenseType:
        type: string
        description: LicenseType, is unique enum value for a license
        enum:
          - TEMPORARY
          - PERMANENT
      structureType:
        type: string
        description: StructureType and Structure subtype, this mdms data.
        maxLength: 64
        minLength: 2
      tradeType:
        type: string
        description: value from Trade type master of mdms .
        maxLength: 64
        minLength: 2
      accessoryCategory:
        type: string
        description: Accessory Category is a master from mdms .
        maxLength: 64
        minLength: 2
      type:
        type: string
        description:  Type will define the rate value is flat amount or rate.
        enum:
          - RATE
          - FLAT
      rate:
        type: string
        description: Rate of the trade license, this can be the rate of flat amount based on type.
        maxLength: 64
        minLength: 2
      uom:
        type: string
        description: unit of measurement of trade type.
        maxLength: 32
        minLength: 2
      from:
        type: string
        description: uom value lower bound.
        maxLength: 64
        minLength: 2
      to:
        type: string
        description: uom value upper bound.
        maxLength: 64
        minLength: 2
    required:
      - tenantId
  CalculationReq:
    type: object
    properties:
      RequestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/RequestInfo'
      CalulationCriteria:
        type: array
        maximum: 100
        items:
          $ref: '#/definitions/CalulationCriteria'
    required:
      - RequestInfo
      - calulationCriteria
  CalculationRes:
    type: object
    properties:
      ResponseInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
      Calculation:
        type: array
        items:
          $ref: '#/definitions/Calculation'
  BillingSlabReq:
    type: object
    properties:
      RequestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/RequestInfo'
      BillingSlab:
        type: array
        maximum: 100
        items:
          $ref: '#/definitions/BillingSlab'
    required:
      - RequestInfo
      - billingSlab
  BillingSlabRes:
    type: object
    properties:
      ResponseInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ResponseInfo'
      BillingSlab:
        type: array
        items:
          $ref: '#/definitions/BillingSlab'
          