swagger: '2.0'

info:
  version: "1.1.0"
  title: Egov otp service
  description: Egov-otp service APIs - contains create , validate and search end point 
  contact:
    name: eGov
    email: info@egovernments.org
  
basePath: "/egov-otp/v110"
x-common-path: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml'
x-api-id: 'org.egov.egov-otp'
#########################################################################################

paths:
    /otp/v1/_create:
      post:
        summary: create OTP Configuration entry
        description: create OTP Configuration this API is internaly call from v1/_send end point, this  end point present in user-otp service no need of explicity call
        tags:
          - OTPConfig
        parameters:
          - name: OTPConfig
            in: body
            description: required parameters have to be populated
            required: true
            schema:
              $ref: '#/definitions/CreateOTPConfigReq'
        responses:
          '200':
            description: Request acknowledged sucessfully
            schema:
              $ref: "#/definitions/OTPConfigRes"
          '400':
            description: Request failed
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
#########################################################################################

    /otp/v1/_validate:
      post:
        summary: validate OTP Configuration entry
        description: validate OTP Configuration this end point is validate the otp respect to mobilenumber
        tags:
          - OTPConfig
        parameters:
          - name: OTPConfig
            in: body
            description: required parameters have to be populated
            required: true
            schema:
              $ref: '#/definitions/CreateOTPConfigReq'
        responses:
          '200':
            description: Request acknowledged sucessfully
            schema:
              $ref: "#/definitions/OTPConfigRes"
          '400':
            description: Request failed
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes' 
#########################################################################################

    /otp/v1/_search:
      post:
        summary: search OTP Configuration entry using uuid
        description: search the mobile number and otp using uuid ,uuid nothing but otp reference number
        tags:
          - OTPConfig
        parameters:
          - name: OTPConfig
            in: body
            description: required parameters have to be populated
            required: true
            schema:
              $ref: '#/definitions/CreateOTPConfigReq'
        responses:
          '200':
            description: Request acknowledged sucessfully
            schema:
              $ref: "#/definitions/OTPConfigRes"
          '400':
            description: Request failed
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'          
#########################################################################################

definitions:
  Createotp:
      type: object
      properties:
        otp:
         type: string 
         description : this is the five digit otp number ,this is mandatory in validate end point should pass otp value in  /otp/v1/_validate end point, in other end point it is read only
        uuid:
          type: string
          description : this is otp reference id, this is mandatory in search end point (/otp/v1/_search), and in other end point it is read only.
        identity: 
          type: string
          description: identity is  username or mobile number. this is  mandatory field in create and validate end point end point is(/otp/v1/_create, and /otp/v1/_validat) and optional field in /otp/v1/_search end point
        tenantId: 
          type: string
          description: Unique Identifier of the tenantId to which user primarily belongs and it is mandatory field in all the end points shoiuld pass this value
        isValidationSuccessful:
          type: string
          description: it return true or false  this is optional or read only property in all end point,
      required:
        - identity
        - tenantId
#########################################################################################

  CreateOTPConfigReq:
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
        otp:
          $ref: '#/definitions/Createotp'
      required:
        - RequestInfo
        - otp

#########################################################################################
  OTPConfigRes:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
        otp:
          type: array
          maximum: 20
          items:
            $ref: '#/definitions/Createotp'
  
    
   