openapi: 3.0.1
info:
  title: PDF-Service APIs
  description: |
    APIs available in PDF-Service
  contact:
    name: eGovernments Foundation
  version: 1.1.0
servers:
- url: /pdf-service/v1/
paths:
  /_create:
    post:
      tags:
      - PDF-Service endpoints
      summary: Generate PDF and store output pdfs to filestore and return their filestoreids.
        The information is also saved into DB so that using _search endpoint we can
        retrieve already generated pdfs.
      description: Generate pdfs and return their filestoreids
      parameters:
      - name: tenantId
        in: query
        description: tenantId for pdf
        required: true
        schema:
          type: string
      - name: key
        in: query
        description: key to identify correct PDF configurarion
        required: true
        schema:
          type: string
      requestBody:
        description: requestinfo object with input json for pdf
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/PDFRequest'
        required: false
      responses:
        201:
          description: PDF successfully created and response sent back
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PDFResponse'
        400:
          description: Incorrect request
          content: {}
        404:
          description: PDF with search parameters was not found
          content: {}
        500:
          description: Error happened at server
          content: {}
      x-codegen-request-body-name: requestbody
  /_createnosave:
    post:
      tags:
      - PDF-Service endpoints
      summary: Generates pdf without storing any information on filestore or in DB.
        The generated pdf would be returned as binary response
      description: Generate pdf and return as binary response
      parameters:
      - name: tenantId
        in: query
        description: tenantId for pdf
        required: true
        schema:
          type: string
      - name: key
        in: query
        description: key to identify correct PDF configurarion
        required: true
        schema:
          type: string
      requestBody:
        description: requestinfo object with input json for pdf
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/PDFRequest'
        required: false
      responses:
        201:
          description: PDF created and returned in binary
          content: {}
        400:
          description: If correct request not sent
          content: {}
        500:
          description: Error occurred at server
          content: {}
      x-codegen-request-body-name: requestbody
  /_search:
    post:
      tags:
      - PDF-Service endpoints
      summary: Get filestoreids and other information about already generated pdf
        by searching on jobid or entityid with other optional search parameters
      description: Get details for already generated PDF
      parameters:
      - name: tenantid
        in: query
        description: tenantId for pdf
        schema:
          type: string
      - name: jobid
        in: query
        description: search based on unique id of pdf job.
        required: true
        schema:
          type: string
      - name: entityid
        in: query
        description: search based on unique id of a document
        required: true
        schema:
          type: string
      - name: isconsolidated
        in: query
        description: Whether single object or multiobject pdf required
        schema:
          type: string
      requestBody:
        description: requestinfo object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/RequestInfo'
        required: false
      responses:
        200:
          description: Pdf information successfully retrieved
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PDFResponse'
        400:
          description: Incorrect request
          content: {}
        404:
          description: PDF with search parameters was not found
          content: {}
        500:
          description: Error happened at server
          content: {}
      x-codegen-request-body-name: requestInfo
  /_getUnrigesteredCodes:
    post:
      tags:
      - PDF-Service endpoints
      summary: Get unregister localisation code which are not present in the system
      description: Get unregister localisation code
      requestBody:
        description: requestinfo object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/RequestInfo'
        required: false
      responses:
        200:
          description: shows unregister localisation code
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UnrigesteredCodesResponse'
        400:
          description: Error while retreving the codes
          content: {}
        404:
          description: Incorrect request
          content: {}
        500:
          description: Error happened at server
          content: {}
      x-codegen-request-body-name: requestInfo
  /_clearUnrigesteredCodes:
    post:
      tags:
      - PDF-Service endpoints
      summary: Clear the unregister localisation code list, removed the localisation code from list which are present in the system
      description: Clear the unregister localisation code list
      requestBody:
        description: requestinfo object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/RequestInfo'
        required: true
      responses:
        200:
          description: shows unregister localisation code
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UnrigesteredCodesResponse'
        400:
          description: Error while retreving the codes
          content: {}
        404:
          description: Incorrect request
          content: {}
        500:
          description: Error happened at server
          content: {}
      x-codegen-request-body-name: requestInfo
  /_getBulkPdfRecordsDetails:
    post:
      tags:
      - Bulk PDF-Service endpoints
      summary: Shows the details of bulk pdf process trigged by an employee.
      description: Shows the details of bulk pdf process
      parameters:
      - name: offset
        in: query
        description: offset for the record search
        schema:
          type: string
        required: false
      - name: jobid
        in: query
        description: search based on unique id of bulk pdf job.
        required: false
        schema:
          type: string
      - name: limit
        in: query
        description: limit for the record search
        required: false
        schema:
          type: string
      requestBody:
        description: requestinfo object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/RequestInfo'
        required: true
      responses:
        200:
          description: Shows the details of bulk pdf process
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/groupBillrecordsResponse'
        400:
          description: Error while retreving the details
          content: {}
        404:
          description: Incorrect request
          content: {}
        500:
          description: Group bill pdf records details are not present for the employee
          content: {}
      x-codegen-request-body-name: requestInfo
  /_deleteBulkPdfRecordsDetails:
    post:
      tags:
      - Bulk PDF-Service endpoints
      summary: Delete the bulk pdf process details trigged by an employee.
      description: Delete the bulk pdf process details.
      requestBody:
        description: requestinfo object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/RequestInfo'
        required: false
      responses:
        200:
          description: "Bulk PDF records details are clear"
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/deleteBillrecordsResponse'
            
        400:
          description: Error while retreving the details
          content: {}
        404:
          description: Incorrect request
          content: {}
        500:
          description: Error happened at server
          content: {}
      x-codegen-request-body-name: requestInfo
  /_cancelProcess:
    post:
      tags:
      - Bulk PDF-Service endpoints
      summary: Cancel the bulk pdf process details trigged by an employee.
      description: Cancel the bulk pdf process details.
      parameters:
      - name: jobid
        in: query
        description: Cancel based on unique id of bulk pdf job.
        required: true
        schema:
          type: string
      requestBody:
        description: requestinfo object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/RequestInfo'
        required: false
      responses:
        200:
          description: "Bulk PDF process with job id: XYZ is cancel"
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/deleteBillrecordsResponse'
            
        400:
          description: jobid or userid can not be empty
          content: {}
        404:
          description: Incorrect request
          content: {}
        500:
          description: Error while clearing the Bulk PDF records details
          content: {}
      x-codegen-request-body-name: requestInfo
  
components:
  schemas:
    PDFResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: '#/components/schemas/ResponseInfo'
        message:
          type: string
        filestoreIds:
          type: array
          description: filestoreids of PDFs from filestore service
          items:
            type: string
        jobid:
          type: string
          description: jobid of pdf create request
        createdtime:
          type: number
          description: start time of job
        endtime:
          type: number
          description: end time of job
        tenantid:
          type: string
        totalcount:
          type: number
        key:
          type: string
          description: key to be used to pick pdf configs
        documentType:
          type: string
          description: documentype defined in pdf config
        moduleName:
          type: string
          description: modulename defined in pdf config
    Role:
      required:
      - code
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        code:
          type: string
    User:
      required:
      - emailId
      - id
      - mobileNumber
      - name
      - roles
      - tenantId
      - type
      - userName
      - uuid
      type: object
      properties:
        id:
          type: integer
          format: int64
        userName:
          type: string
        name:
          type: string
        type:
          type: string
        mobileNumber:
          type: string
        emailId:
          type: string
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
        tenantId:
          type: string
        uuid:
          type: string
    ResponseInfo:
      type: object
      properties:
        apiId:
          type: string
        ver:
          type: string
        ts:
          type: number
        resMsgId:
          type: string
        msgId:
          type: string
        status:
          type: string
        correlationId:
          type: string
        userInfo:
          $ref: '#/components/schemas/User'
    RequestInfo:
      required:
      - action
      - apiId
      - authToken
      - correlationId
      - did
      - key
      - msgId
      - ts
      - userInfo
      - ver
      type: object
      properties:
        apiId:
          type: string
        ver:
          type: string
        ts:
          type: integer
          format: int64
        action:
          type: string
        did:
          type: string
        key:
          type: string
        msgId:
          type: string
        authToken:
          type: string
        correlationId:
          type: string
        userInfo:
          $ref: '#/components/schemas/User'
    PDFRequest:
      type: object
      properties:
        ResponseInfo:
          $ref: '#/components/schemas/RequestInfo'
        moduleObjectWithName:
          type: object
          properties: {}
    UnrigesteredCodesResponse:
      properties:
        ResponseInfo:
          $ref: '#/components/schemas/ResponseInfo'
        unregisteredLocalisationCodes:
          type: array
          description: List of unregistered localisation codes
          items:
            type: string
    groupBillrecordsResponse:
      properties:
        ResponseInfo:
          $ref: '#/components/schemas/ResponseInfo'
        groupBillrecords:
          $ref: '#/components/schemas/groupBillrecords'
    groupBillrecords:
      type: object
      properties:
        jobid:
          type: string
          description: jobid of pdf create request.
        uuid:
          type: string
          description: uuid of employee who request for bulk pdf.
        totalrecords:
          type: string
          description: total records in pdf bulk create request.
        recordscompleted:
          type: string
          description: Number of records completed in pdf bulk create request.
        filestoreid:
          type: string
          description: filestoreid of pdf bulk create request.
        createdBy:
          type: string
          description: username (preferred) or userid of the user that created the object
        lastModifiedBy:
          type: string
          description: username (preferred) or userid of the user that last modified the
            object
        createdTime:
          type: integer
          format: int64
          description: epoch of the time object is created
        lastModifiedTime:
          type: integer
          format: int64
          description: epoch of the time object is last modified
        tenantid:
          type: string
          description: tenantid of the ulb.
        locality:
          type: string
          description: locality area code of the ulb.
        bussinessService:
          type: string
          description: Business service for which bulk pdf is requested.
        consumercode:
          type: string
          description: consumer code of the application.
        isConsolidated:
          type: string
          description: Boolean flag to show records from multiple modules
        status:
          type: string
          description: progess of the bulk pdf process.
    deleteBillrecordsResponse:
      properties:
        ResponseInfo:
          $ref: '#/components/schemas/ResponseInfo'
        Message:
          type: string