swagger: '2.0'
info:
  version: 1.0.0
  title: Birth Registration Service.
  description: |
    This service provides APIs to register new births in the system.
  contact:
    name: eGovernments Foundation
    email: contacts@egovernments.org
schemes:
  - https
basePath: /birth-services
x-api-id: org.egov.birth.services
x-common-path: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml
paths:
  /v1/registration/_search:
    post:
      summary: Get the list of Birth registration applications
      description: 1. Search and get birth registration applications(s) based on defined search criteria. 2. In case multiple parameters are passed voter registration applications will be searched as an AND combination of all the parameters.
      parameters:
        - $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/parameters/requestInfo
        - $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/parameters/tenantId
        - name: status
          in: query
          description: Search based on status.
          type: string
          allowEmptyValue: true
        - name: ids
          type: array
          items:
            type: integer
            format: int64
          in: query
          maxItems: 50
          description: unique identifier of birth registration
        - name: applicationNumber
          in: query
          description: Unique application number for the Birth Registration Application
          type: string
          minLength: 2
          maxLength: 64
      responses:
        '200':
          description: Birth registration applications(s) Retrived Successfully
          schema:
            $ref: '#/definitions/BirthRegistrationRequest'
        '400':
          description: Invalid input
          schema:
            $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
      tags:
        - Birth Registration Application
  /v1/registration/_create:
    post:
      summary: Create new Birth Registration Application
      description: |
        To create new birth registration applications in the system. API supports bulk creation with max limit as defined in the Birth Registration Request. Please note that either whole batch succeeds or fails, there's no partial batch success. 
          
      parameters:
        - name: BirthRegistrationRequest
          in: body
          description: Details for the new Birth Registration Application(s) + RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/BirthRegistrationRequest'
      responses:
        '201':
          description: ReponseInfo with Birth Registration Application(s) created successfully
          schema:
            $ref: '#/definitions/BirthRegistrationResponse'
        '400':
          description: Birth Registration Application(s) creation failed
          schema:
            $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
      tags:
        - Birth Registration Application
  /v1/registration/_update:
    post:
      summary: update existing Birth Registration Applications.
      description: |
        To update existing birth registration applications in the system. API supports bulk updation with max limit as defined in the birth registration Request. Please note that either whole batch succeeds or fails, there's no partial batch success.
      parameters:
        - name: BirthRegistrationRequest
          in: body
          description: Details for the new (s) + RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/BirthRegistrationRequest'
      responses:
        '201':
          description: ReponseInfo with Birth Registration Application(s) updated sudcessfully
          schema:
            $ref: '#/definitions/BirthRegistrationResponse'
        '400':
          description: (s) updation failed
          schema:
            $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
      tags:
        - Birth Registration Application
definitions:
  Applicant:
    description: Details of the user applying for birth registration
    allOf:
      - $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/egov-user/contracts/v1-0-0.yml#/definitions/User
  BirthRegistrationApplication:
    type: object
    description: A Object holds the basic data for a Birth Registration Application
    properties:
      id:
        type: string
        minLength: 2
        maxLength: 64
        description: Unique Identifier of the Birth Registration Application (UUID)
        readOnly: true
      tenantId:
        type: string
        description: Unique Identifier of ULB
        maxLength: 128
        minLength: 2
      applicationNumber:
        type: string
        description: Unique application number
        maxLength: 128
        minLength: 2
        readOnly: true
      babyFirstName:
        type: string
        description: Baby’s first name
        maxLength: 128
        minLength: 2
      babyLastName:
        type: string
        description: Baby’s last name
        maxLength: 128
        minLength: 2
      fatherOfApplicant:
        type: string
        description: Name of father
        maxLength: 128
        minLength: 2
      motherOfApplicant:
        type: string
        description: Name of mother
        maxLength: 128
        minLength: 2
      fatherMobileNumber:
        type: string
        description: Number of father
        maxLength: 128
        minLength: 2
      motherMobileNumber:
        type: string
        description: Number of mother
        maxLength: 128
        minLength: 2  
      doctorName:
        type: string
        description: Name of doctor
        maxLength: 128
        minLength: 2
      hospitalName:
        type: string
        description: Name of hospital
        maxLength: 128
        minLength: 2
      placeOfBirth:
        type: string
        description: Place of birth
        maxLength: 128
        minLength: 2
      timeOfBirth:
        type: integer
        description: Date of birth epoch
      address:
        $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/Address  
      applicant:
        $ref: '#/definitions/Applicant'  
      auditDetails:
        $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/AuditDetails
    required:
      - tenantId
      - applicant
      - babyFirstName
      - babyLastName
      - fatherOfApplicant
      - motherOfApplicant
      - fatherMobileNumber
      - motherMobileNumber
      - doctorName
      - hospitalName
      - placeOfBirth
      - timeOfBirth
  Workflow:
    type: object
    description: Fields related to workflow service
    properties:
      action:
        type: string
        description: Action on the application in certain
        minLength: 1
        maxLength: 64
      status:
        type: string
        description: status of the application
      comments:
        type: string
        description: Unique Identifier scrutinized number
        minLength: 1
        maxLength: 64
      documents:
        description: Attach the workflow verification documents.
        type: array
        items:
          $ref: https://raw.githubusercontent.com/egovernments/municipal-services/common-contract/docs/common-contract-v2-0-0.yml#/components/schemas/Document
  BirthRegistrationRequest:
    description: Contract class to receive request. Array of  items are used in case of create, whereas single  item is used for update
    properties:
      RequestInfo:
        $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/RequestInfo
      BirthRegistrationApplications:
        description: Used for search result and create only
        type: array
        minimum: 1
        maximum: 100
        items:
          $ref: '#/definitions/BirthRegistrationApplication'
  BirthRegistrationResponse:
    description: Contract class to send response. Array of  items are used in case of search results or response for create, whereas single  item is used for update
    properties:
      ResponseInfo:
        $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ResponseInfo
      BirthRegistrationApplications:
        description: Used for search result and create only
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/BirthRegistrationApplication'
